name: Update Environment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'environment.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'environment.yml'
      - 'Dockerfile'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: eculler/example_env:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
