name: Update Environment

on: workflow_dispatch
#   push:
#     branches: [ "main" ]
#     paths:
#       - 'environment.yml'
#       - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: eculler/example_env:${GITHUB_REF##*/}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
